### ISSUE TITLE
The library needs a POST method for Commerce CLI commands

### ISSUE THREAD

**Issue by thoughtassassin** [adobe/aio-lib-cloudmanager#177]
Commerce support is being added to the CLI. It will need a POST method to support Commerce CLI commands.

**Comment by justinedelson** [comment]
@rwalter215 per https://github.com/adobe/aio-cli-plugin-cloudmanager/blob/2.2.2/src/base-commerce-cli-command.js#L36, a get method is also necessary to make the CLI Plugin functional. Wouldn't that be expected to be done together so that the the CLI Plugin can depend upon the version of the lib that has both?

**Comment by thoughtassassin** [comment]
@justinedelson Jason just submitted a PR for GET
